export default {
  "CHECKBOX.BORDER_RADIUS": { ref: "BASICS.BORDER_RADII.S" },
  "CHECKBOX.BACKGROUND_COLOR": {
    ref: "COLOR_SCHEME.COMPONENT.BACKGROUND_COLOR"
  },
  "CHECKBOX.BORDER_WIDTH": { ref: "INPUT.BORDER_BOTTOM_WIDTH" },
  "CHECKBOX.BORDER_COLOR": {
    ref: "BASICS.COLORS.CHARCOAL_600",
    transform: { alpha: 0.5 }
  },
  "CHECKBOX.HALO.COLOR": { ref: "INPUT.HALO.COLOR" },
  "CHECKBOX.HALO.WIDTH": { ref: "INPUT.HALO.WIDTH" },
  "CHECKBOX.LABEL_SPACING": { ref: "DENSITY.SPACINGS.S" },

  // Hover
  "CHECKBOX.HOVER.BORDER_COLOR": {
    ref: "BASICS.COLORS.CHARCOAL_600",
    transform: { alpha: 0.5 }
  },
  "CHECKBOX.HOVER.HALO.WIDTH": { ref: "INPUT.HOVER.HALO.WIDTH" },
  "CHECKBOX.HOVER.HALO.COLOR": { ref: "INPUT.HALO.COLOR" },

  // Focus
  "CHECKBOX.FOCUS.BORDER_COLOR": {
    ref: "BASICS.COLORS.CHARCOAL_600",
    transform: { alpha: 0.5 }
  },
  "CHECKBOX.FOCUS.HALO.COLOR": { ref: "INPUT.FOCUS.HALO.COLOR" },
  "CHECKBOX.FOCUS.HALO.WIDTH": { ref: "INPUT.FOCUS.HALO.WIDTH" },

  // Active
  "CHECKBOX.ACTIVE.BORDER_COLOR": {
    ref: "BASICS.COLORS.CHARCOAL_600",
    transform: { alpha: 0.5 }
  },
  "CHECKBOX.ACTIVE.HALO.COLOR": { ref: "INPUT.ACTIVE.HALO.COLOR" },
  "CHECKBOX.ACTIVE.HALO.WIDTH": { ref: "INPUT.ACTIVE.HALO.WIDTH" },

  // Checked
  "CHECKBOX.CHECKED.BORDER_COLOR": { ref: "BASICS.COLORS.CHARCOAL_600" },
  "CHECKBOX.CHECKED.ICON_COLOR": { ref: "BASICS.COLORS.WHITE" },
  "CHECKBOX.CHECKED.BACKGROUND_COLOR": { ref: "BASICS.COLORS.CHARCOAL_600" },

  // Disabled
  "CHECKBOX.DISABLED.BORDER_COLOR": {
    ref: "INPUT.DISABLED.BORDER_COLOR"
  },

  // Disabled + Checked
  "CHECKBOX.DISABLED.CHECKED.BACKGROUND_COLOR": {
    ref: "BASICS.COLORS.CHARCOAL_600",
    transform: { alhpa: 0.5 }
  }
};
