export default {
  "FORM_FIELD.INSTRUCTIONAL_TEXT.FONT_SIZE": { ref: "DENSITY.FONT_SIZES.S" },
  "FORM_FIELD.INSTRUCTIONAL_TEXT.FONT_WEIGHT": {
    ref: "BASICS.FONT_WEIGHTS.REGULAR"
  },
  "FORM_FIELD.INSTRUCTIONAL_TEXT.FONT_FAMILY": {
    ref: "BASICS.FONT_FAMILIES.MAIN"
  },
  "FORM_FIELD.INSTRUCTIONAL_TEXT.FONT_COLOR": { abstract: true },
  "FORM_FIELD.INSTRUCTIONAL_TEXT.LINE_HEIGHT": { ref: "BASICS.LINE_HEIGHTS.M" },
  "FORM_FIELD.ICON.WIDTH": { ref: "ICON.WIDTH" },
  "FORM_FIELD.ICON.PADDING_RIGHT": { ref: "DENSITY.SPACINGS.S" },
  "FORM_FIELD.ICON.COLOR": { ref: "COLOR_SCHEME.TEXT_COLOR" }
};
