export default {
  "INPUT.MIN_HEIGHT": { ref: "DENSITY.INPUT.MIN_HEIGHT" },
  "INPUT.VERTICAL_PADDING": { ref: "DENSITY.INPUT.VERTICAL_PADDING" },
  "INPUT.DENSITY_MEDIUM_MIN_HEIGHT": "24px",
  "INPUT.GRID_GUTTER_WIDTH": { ref: "DENSITY.SPACINGS.S" },
  "INPUT.BORDER_RADIUS": { ref: "BASICS.BORDER_RADII.S" },
  "INPUT.BORDER_COLOR": {
    ref: "COLOR_SCHEME.SURFACE_LEVEL_1_5_COLOR"
  },
  "INPUT.DISABLED.BORDER_COLOR": {
    ref: "COLOR_SCHEME.SURFACE_LEVEL_1_5_COLOR"
  },
  "INPUT.BORDER_BOTTOM_COLOR": { abstract: true },
  "INPUT.BORDER_BOTTOM_WIDTH": { ref: "BASICS.BORDER_WIDTHS.S" },
  "INPUT.HOVER.BORDER_BOTTOM_COLOR": { abstract: true },
  "INPUT.FOCUS.BORDER_BOTTOM_COLOR": { abstract: true },
  "INPUT.FONT_COLOR": { ref: "COLOR_SCHEME.TEXT_COLOR" },
  "INPUT.DISABLED.FONT_COLOR": {
    ref: "COLOR_SCHEME.TEXT_COLOR",
    transform: { alpha: 0.2 }
  },
  "INPUT.HALO.COLOR": { abstract: true },
  "INPUT.HALO.WIDTH": { ref: "BASICS.BORDER_WIDTHS.NONE" },
  "INPUT.HOVER.HALO.WIDTH": { ref: "BASICS.BORDER_WIDTHS.L" },
  "INPUT.FOCUS.HALO.WIDTH": { ref: "BASICS.BORDER_WIDTHS.L" },
  "INPUT.FOCUS.HALO.COLOR": { abstract: true },
  "INPUT.ACTIVE.HALO.WIDTH": { ref: "BASICS.BORDER_WIDTHS.L" },
  "INPUT.ACTIVE.HALO.COLOR": { abstract: true },
  "INPUT.FONT_WEIGHT": { ref: "BASICS.FONT_WEIGHTS.MEDIUM" },
  "INPUT.FONT_FAMILY": { ref: "BASICS.FONT_FAMILIES.MAIN" },
  "INPUT.HORIZONTAL_PADDING": 0,
  "INPUT.GUTTER_WIDTH": { ref: "DENSITY.SPACINGS.XS" },
  "INPUT.FONT_SIZE": { ref: "DENSITY.FONT_SIZES.M" },
  "INPUT.LINE_HEIGHT": { ref: "BASICS.LINE_HEIGHTS.M" },
  "INPUT.PLACEHOLDER.FONT_COLOR": { ref: "COLOR_SCHEME.TEXT_COLOR_DIM" }
};
