export default {
  "SPACINGS.XXS": { ref: "BASICS.SPACINGS.LOW_XXS" },
  "SPACINGS.XS": { ref: "BASICS.SPACINGS.LOW_XS" },
  "SPACINGS.S": { ref: "BASICS.SPACINGS.LOW_S" },
  "SPACINGS.M": { ref: "BASICS.SPACINGS.LOW_M" },
  "SPACINGS.L": { ref: "BASICS.SPACINGS.LOW_L" },
  "SPACINGS.XL": { ref: "BASICS.SPACINGS.LOW_XL" },
  "SPACINGS.XXL": { ref: "BASICS.SPACINGS.LOW_XXL" },
  "FONT_SIZES.S": { ref: "BASICS.FONT_SIZES.LOW_S" },
  "FONT_SIZES.M": { ref: "BASICS.FONT_SIZES.LOW_M" },
  "FONT_SIZES.L": { ref: "BASICS.FONT_SIZES.LOW_L" },
  "FONT_SIZES.XL": { ref: "BASICS.FONT_SIZES.LOW_XL" },
  "FONT_SIZES.XXL": { ref: "BASICS.FONT_SIZES.LOW_XXL" }
};
