export default {
  INPUT_BORDER_BOTTOM_COLOR: { ref: "BASICS.COLORS.CHARCOAL_600", alpha: 0.5 },
  INPUT_BORDER_BOTTOM_HOVER_COLOR: { ref: "BASICS.COLORS.CHARCOAL_600" },
  INPUT_BORDER_BOTTOM_FOCUS_COLOR: { ref: "COLOR_SCHEME.ACCENT_COLOR_500" },
  INPUT_HALO_COLOR: { ref: "BASICS.COLORS.CHARCOAL_600", alpha: 0.15 },
  INPUT_HALO_FOCUS_COLOR: { ref: "COLOR_SCHEME.ACCENT_COLOR_500", alpha: 0.25 },
  INPUT_HALO_ACTIVE_COLOR: { ref: "COLOR_SCHEME.ACCENT_COLOR_500", alpha: 0.25 }
};
