export default {
  "surfaceLevel1Color": { type: "color" },
  "surfaceLevel15Color": { type: "color" },
  "surfaceLevel2Color": { type: "color" },
  "surfaceLevel3Color": { type: "color" },
  "surfaceLevel4Color": { type: "color" },
  "accentColor100": { type: "color" },
  "accentColor200": { type: "color" },
  "accentColor300": { type: "color" },
  "accentColor400": { type: "color" },
  "accentColor500": { type: "color" },
  "accentColor600": { type: "color" },
  "accentColor700": { type: "color" },
  "accentColor800": { type: "color" },
  "accentColor900": { type: "color" },
  "component.backgroundColor": { type: "color" },
  "textColor": { type: "color" },
  "textColorDim": { type: "color" },
  "lowShadowColor": { type: "color" },
  "highShadowColor": { type: "color" }
};
