import ZoomOut16SVG from "./icons/information-dense/zoom-out.svg";
import ZoomIn16SVG from "./icons/information-dense/zoom-in.svg";
import Volume16SVG from "./icons/information-dense/volume.svg";
import Visible16SVG from "./icons/information-dense/visible.svg";
import Upload16SVG from "./icons/information-dense/upload.svg";
import Up16SVG from "./icons/information-dense/up.svg";
import Unlock16SVG from "./icons/information-dense/unlock.svg";
import Undo16SVG from "./icons/information-dense/undo.svg";
import Unavailable16SVG from "./icons/information-dense/unavailable.svg";
import Trash16SVG from "./icons/information-dense/trash.svg";
import Tag16SVG from "./icons/information-dense/tag.svg";
import Sync16SVG from "./icons/information-dense/sync.svg";
import Support16SVG from "./icons/information-dense/support.svg";
import Subscription16SVG from "./icons/information-dense/subscription.svg";
import SocialYoutube16SVG from "./icons/information-dense/social-youtube.svg";
import SocialTwitter16SVG from "./icons/information-dense/social-twitter.svg";
import SocialLinkedin16SVG from "./icons/information-dense/social-linkedin.svg";
import SocialInstagram16SVG from "./icons/information-dense/social-instagram.svg";
import SocialFacebook16SVG from "./icons/information-dense/social-facebook.svg";
import Share16SVG from "./icons/information-dense/share.svg";
import Settings16SVG from "./icons/information-dense/settings.svg";
import Service16SVG from "./icons/information-dense/service.svg";
import Security16SVG from "./icons/information-dense/security.svg";
import Search16SVG from "./icons/information-dense/search.svg";
import Save16SVG from "./icons/information-dense/save.svg";
import Rfi16SVG from "./icons/information-dense/rfi.svg";
import Report16SVG from "./icons/information-dense/report.svg";
import Redo16SVG from "./icons/information-dense/redo.svg";
import Recommend16SVG from "./icons/information-dense/recommend.svg";
import Quantities16SVG from "./icons/information-dense/quantities.svg";
import Publish16SVG from "./icons/information-dense/publish.svg";
import Properties16SVG from "./icons/information-dense/properties.svg";
import ProjectManagement16SVG from "./icons/information-dense/project-management.svg";
import Profile16SVG from "./icons/information-dense/profile.svg";
import ProductsAndServices16SVG from "./icons/information-dense/products-and-services.svg";
import Print16SVG from "./icons/information-dense/print.svg";
import Play16SVG from "./icons/information-dense/play.svg";
import Placeholder16SVG from "./icons/information-dense/placeholder.svg";
import Pin16SVG from "./icons/information-dense/pin.svg";
import Photos16SVG from "./icons/information-dense/photos.svg";
import PermissionIndividual16SVG from "./icons/information-dense/permission-individual.svg";
import PermissionGroup16SVG from "./icons/information-dense/permission-group.svg";
import Pause16SVG from "./icons/information-dense/pause.svg";
import Paste16SVG from "./icons/information-dense/paste.svg";
import OnlineViewers16SVG from "./icons/information-dense/online-viewers.svg";
import Notification16SVG from "./icons/information-dense/notification.svg";
import More16SVG from "./icons/information-dense/more.svg";
import MoreVertical16SVG from "./icons/information-dense/more-vertical.svg";
import ModelCoordination16SVG from "./icons/information-dense/model-coordination.svg";
import Minimize16SVG from "./icons/information-dense/minimize.svg";
import Maximize16SVG from "./icons/information-dense/maximize.svg";
import ManageAccess16SVG from "./icons/information-dense/manage-access.svg";
import Mail16SVG from "./icons/information-dense/mail.svg";
import Lock16SVG from "./icons/information-dense/lock.svg";
import Location16SVG from "./icons/information-dense/location.svg";
import List16SVG from "./icons/information-dense/list.svg";
import Link16SVG from "./icons/information-dense/link.svg";
import Layout16SVG from "./icons/information-dense/layout.svg";
import Item16SVG from "./icons/information-dense/item.svg";
import Issue16SVG from "./icons/information-dense/issue.svg";
import Insight16SVG from "./icons/information-dense/insight.svg";
import Info16SVG from "./icons/information-dense/info.svg";
import Home16SVG from "./icons/information-dense/home.svg";
import Hierarchy16SVG from "./icons/information-dense/hierarchy.svg";
import Hidden16SVG from "./icons/information-dense/hidden.svg";
import Help16SVG from "./icons/information-dense/help.svg";
import Grid16SVG from "./icons/information-dense/grid.svg";
import Globe16SVG from "./icons/information-dense/globe.svg";
import Forward16SVG from "./icons/information-dense/forward.svg";
import Forums16SVG from "./icons/information-dense/forums.svg";
import Folder16SVG from "./icons/information-dense/folder.svg";
import FolderOpen16SVG from "./icons/information-dense/folder-open.svg";
import Flag16SVG from "./icons/information-dense/flag.svg";
import Filter16SVG from "./icons/information-dense/filter.svg";
import FilterTokens16SVG from "./icons/information-dense/filter-tokens.svg";
import FileZip16SVG from "./icons/information-dense/file-zip.svg";
import FileVideo16SVG from "./icons/information-dense/file-video.svg";
import FileSpreadsheet16SVG from "./icons/information-dense/file-spreadsheet.svg";
import FilePresentation16SVG from "./icons/information-dense/file-presentation.svg";
import FilePdf16SVG from "./icons/information-dense/file-pdf.svg";
import FilePart16SVG from "./icons/information-dense/file-part.svg";
import FileImage16SVG from "./icons/information-dense/file-image.svg";
import FileGeneric16SVG from "./icons/information-dense/file-generic.svg";
import FileDocument16SVG from "./icons/information-dense/file-document.svg";
import FileAssembly16SVG from "./icons/information-dense/file-assembly.svg";
import Field16SVG from "./icons/information-dense/field.svg";
import Feedback16SVG from "./icons/information-dense/feedback.svg";
import Featured16SVG from "./icons/information-dense/featured.svg";
import Favorite16SVG from "./icons/information-dense/favorite.svg";
import External16SVG from "./icons/information-dense/external.svg";
import ExternalLink16SVG from "./icons/information-dense/external-link.svg";
import Export16SVG from "./icons/information-dense/export.svg";
import ExportMove16SVG from "./icons/information-dense/export-move.svg";
import ExpandPanel16SVG from "./icons/information-dense/expand-panel.svg";
import Error16SVG from "./icons/information-dense/error.svg";
import Education16SVG from "./icons/information-dense/education.svg";
import Edit16SVG from "./icons/information-dense/edit.svg";
import DropdownCaretUp16SVG from "./icons/information-dense/dropdown-caret-up.svg";
import DropdownCaretRight16SVG from "./icons/information-dense/dropdown-caret-right.svg";
import DropdownCaretLeft16SVG from "./icons/information-dense/dropdown-caret-left.svg";
import DropdownCaretDown16SVG from "./icons/information-dense/dropdown-caret-down.svg";
import Download16SVG from "./icons/information-dense/download.svg";
import Down16SVG from "./icons/information-dense/down.svg";
import DocumentManagement16SVG from "./icons/information-dense/document-management.svg";
import Devices16SVG from "./icons/information-dense/devices.svg";
import DeviceTablet16SVG from "./icons/information-dense/device-tablet.svg";
import DeviceMobile16SVG from "./icons/information-dense/device-mobile.svg";
import DeviceDesktop16SVG from "./icons/information-dense/device-desktop.svg";
import Dashboard16SVG from "./icons/information-dense/dashboard.svg";
import CtaArrowRight16SVG from "./icons/information-dense/cta-arrow-right.svg";
import CostControl16SVG from "./icons/information-dense/cost-control.svg";
import Copy16SVG from "./icons/information-dense/copy.svg";
import Complete16SVG from "./icons/information-dense/complete.svg";
import Compare16SVG from "./icons/information-dense/compare.svg";
import Comment16SVG from "./icons/information-dense/comment.svg";
import CollapsePanel16SVG from "./icons/information-dense/collapse-panel.svg";
import Collaboration16SVG from "./icons/information-dense/collaboration.svg";
import Cloud16SVG from "./icons/information-dense/cloud.svg";
import ClosedCaptioning16SVG from "./icons/information-dense/closed-captioning.svg";
import Close16SVG from "./icons/information-dense/close.svg";
import CloseSmall16SVG from "./icons/information-dense/close-small.svg";
import Clock16SVG from "./icons/information-dense/clock.svg";
import Checkmark16SVG from "./icons/information-dense/checkmark.svg";
import CheckmarkIndeterminate16SVG from "./icons/information-dense/checkmark-indeterminate.svg";
import Checklist16SVG from "./icons/information-dense/checklist.svg";
import CheckboxIndeterminate16SVG from "./icons/information-dense/checkbox-indeterminate.svg";
import CheckboxChecked16SVG from "./icons/information-dense/checkbox-checked.svg";
import CheckDisabled16SVG from "./icons/information-dense/check-disabled.svg";
import Chat16SVG from "./icons/information-dense/chat.svg";
import CartFull16SVG from "./icons/information-dense/cart-full.svg";
import CartEmpty16SVG from "./icons/information-dense/cart-empty.svg";
import CaretUp16SVG from "./icons/information-dense/caret-up.svg";
import CaretRight16SVG from "./icons/information-dense/caret-right.svg";
import CaretLeft16SVG from "./icons/information-dense/caret-left.svg";
import CaretDown16SVG from "./icons/information-dense/caret-down.svg";
import Calendar16SVG from "./icons/information-dense/calendar.svg";
import BuildingOps16SVG from "./icons/information-dense/building-ops.svg";
import Bookmark16SVG from "./icons/information-dense/bookmark.svg";
import Billing16SVG from "./icons/information-dense/billing.svg";
import Back16SVG from "./icons/information-dense/back.svg";
import Attachment16SVG from "./icons/information-dense/attachment.svg";
import Attach16SVG from "./icons/information-dense/attach.svg";
import Assets16SVG from "./icons/information-dense/assets.svg";
import AreaPost16SVG from "./icons/information-dense/area-post.svg";
import Archive16SVG from "./icons/information-dense/archive.svg";
import Add16SVG from "./icons/information-dense/add.svg";
import AddMember16SVG from "./icons/information-dense/add-member.svg";
import AddFolder16SVG from "./icons/information-dense/add-folder.svg";
import ZoomOut24SVG from "./icons/regular/zoom-out.svg";
import ZoomIn24SVG from "./icons/regular/zoom-in.svg";
import XCloseGray24SVG from "./icons/regular/x-close-gray.svg";
import Volume24SVG from "./icons/regular/volume.svg";
import Visible24SVG from "./icons/regular/visible.svg";
import Upload24SVG from "./icons/regular/upload.svg";
import Up24SVG from "./icons/regular/up.svg";
import Unlock24SVG from "./icons/regular/unlock.svg";
import Undo24SVG from "./icons/regular/undo.svg";
import Unavailable24SVG from "./icons/regular/unavailable.svg";
import Trash24SVG from "./icons/regular/trash.svg";
import Tag24SVG from "./icons/regular/tag.svg";
import Sync24SVG from "./icons/regular/sync.svg";
import Support24SVG from "./icons/regular/support.svg";
import Subscription24SVG from "./icons/regular/subscription.svg";
import SocialYoutube24SVG from "./icons/regular/social-youtube.svg";
import SocialTwitter24SVG from "./icons/regular/social-twitter.svg";
import SocialLinkedin24SVG from "./icons/regular/social-linkedin.svg";
import SocialInstagram24SVG from "./icons/regular/social-instagram.svg";
import SocialFacebook24SVG from "./icons/regular/social-facebook.svg";
import SocialBlog24SVG from "./icons/regular/social-blog.svg";
import SocialBlog224SVG from "./icons/regular/social-blog-2.svg";
import Share24SVG from "./icons/regular/share.svg";
import Settings24SVG from "./icons/regular/settings.svg";
import Service24SVG from "./icons/regular/service.svg";
import Security24SVG from "./icons/regular/security.svg";
import Search24SVG from "./icons/regular/search.svg";
import Save24SVG from "./icons/regular/save.svg";
import Rfi24SVG from "./icons/regular/rfi.svg";
import Report24SVG from "./icons/regular/report.svg";
import Redo24SVG from "./icons/regular/redo.svg";
import Recommend24SVG from "./icons/regular/recommend.svg";
import Quantities24SVG from "./icons/regular/quantities.svg";
import Publish24SVG from "./icons/regular/publish.svg";
import Properties24SVG from "./icons/regular/properties.svg";
import ProjectManagement24SVG from "./icons/regular/project-management.svg";
import Profile24SVG from "./icons/regular/profile.svg";
import ProductsAndServices24SVG from "./icons/regular/products-and-services.svg";
import Print24SVG from "./icons/regular/print.svg";
import Play24SVG from "./icons/regular/play.svg";
import Placeholder24SVG from "./icons/regular/placeholder.svg";
import Pin24SVG from "./icons/regular/pin.svg";
import Photos24SVG from "./icons/regular/photos.svg";
import PermissionIndividual24SVG from "./icons/regular/permission-individual.svg";
import PermissionGroup24SVG from "./icons/regular/permission-group.svg";
import Pause24SVG from "./icons/regular/pause.svg";
import Paste24SVG from "./icons/regular/paste.svg";
import OnlineViewers24SVG from "./icons/regular/online-viewers.svg";
import Notification24SVG from "./icons/regular/notification.svg";
import More24SVG from "./icons/regular/more.svg";
import MoreVertical24SVG from "./icons/regular/more-vertical.svg";
import ModelCoordination24SVG from "./icons/regular/model-coordination.svg";
import Minimize24SVG from "./icons/regular/minimize.svg";
import Maximize24SVG from "./icons/regular/maximize.svg";
import ManageAccess24SVG from "./icons/regular/manage-access.svg";
import Mail24SVG from "./icons/regular/mail.svg";
import Lock24SVG from "./icons/regular/lock.svg";
import Location24SVG from "./icons/regular/location.svg";
import List24SVG from "./icons/regular/list.svg";
import Link24SVG from "./icons/regular/link.svg";
import Layout24SVG from "./icons/regular/layout.svg";
import Item24SVG from "./icons/regular/item.svg";
import Issue24SVG from "./icons/regular/issue.svg";
import Insight24SVG from "./icons/regular/insight.svg";
import Info24SVG from "./icons/regular/info.svg";
import Home24SVG from "./icons/regular/home.svg";
import Hierarchy24SVG from "./icons/regular/hierarchy.svg";
import Hidden24SVG from "./icons/regular/hidden.svg";
import Help24SVG from "./icons/regular/help.svg";
import Hamburger24SVG from "./icons/regular/hamburger.svg";
import HamburgerDefault24SVG from "./icons/regular/hamburger-default.svg";
import HamburgerClose24SVG from "./icons/regular/hamburger-close.svg";
import Grid24SVG from "./icons/regular/grid.svg";
import Globe24SVG from "./icons/regular/globe.svg";
import Forward24SVG from "./icons/regular/forward.svg";
import Forums24SVG from "./icons/regular/forums.svg";
import Folder24SVG from "./icons/regular/folder.svg";
import FolderOpen24SVG from "./icons/regular/folder-open.svg";
import Flag24SVG from "./icons/regular/flag.svg";
import Filter24SVG from "./icons/regular/filter.svg";
import FilterTokens24SVG from "./icons/regular/filter-tokens.svg";
import FileZip24SVG from "./icons/regular/file-zip.svg";
import FileVideo24SVG from "./icons/regular/file-video.svg";
import FileSpreadsheet24SVG from "./icons/regular/file-spreadsheet.svg";
import FilePresentation24SVG from "./icons/regular/file-presentation.svg";
import FilePdf24SVG from "./icons/regular/file-pdf.svg";
import FilePart24SVG from "./icons/regular/file-part.svg";
import FileImage24SVG from "./icons/regular/file-image.svg";
import FileGeneric24SVG from "./icons/regular/file-generic.svg";
import FileDocument24SVG from "./icons/regular/file-document.svg";
import FileAssembly24SVG from "./icons/regular/file-assembly.svg";
import Field24SVG from "./icons/regular/field.svg";
import Feedback24SVG from "./icons/regular/feedback.svg";
import Featured24SVG from "./icons/regular/featured.svg";
import Favorite24SVG from "./icons/regular/favorite.svg";
import External24SVG from "./icons/regular/external.svg";
import ExternalLink24SVG from "./icons/regular/external-link.svg";
import Export24SVG from "./icons/regular/export.svg";
import ExportMove24SVG from "./icons/regular/export-move.svg";
import Expand24SVG from "./icons/regular/expand.svg";
import ExpandPanel24SVG from "./icons/regular/expand-panel.svg";
import Error24SVG from "./icons/regular/error.svg";
import Education24SVG from "./icons/regular/education.svg";
import Edit24SVG from "./icons/regular/edit.svg";
import Download24SVG from "./icons/regular/download.svg";
import Down24SVG from "./icons/regular/down.svg";
import DoubleCaret24SVG from "./icons/regular/double-caret.svg";
import DocumentManagement24SVG from "./icons/regular/document-management.svg";
import Devices24SVG from "./icons/regular/devices.svg";
import DeviceTablet24SVG from "./icons/regular/device-tablet.svg";
import DeviceMobile24SVG from "./icons/regular/device-mobile.svg";
import DeviceDesktop24SVG from "./icons/regular/device-desktop.svg";
import Dashboard24SVG from "./icons/regular/dashboard.svg";
import CtaArrowRight24SVG from "./icons/regular/cta-arrow-right.svg";
import CostControl24SVG from "./icons/regular/cost-control.svg";
import Copy24SVG from "./icons/regular/copy.svg";
import Complete24SVG from "./icons/regular/complete.svg";
import Compare24SVG from "./icons/regular/compare.svg";
import Comment24SVG from "./icons/regular/comment.svg";
import Collapse24SVG from "./icons/regular/collapse.svg";
import CollapsePanel24SVG from "./icons/regular/collapse-panel.svg";
import Collaboration24SVG from "./icons/regular/collaboration.svg";
import Cloud24SVG from "./icons/regular/cloud.svg";
import ClosedCaptioning24SVG from "./icons/regular/closed-captioning.svg";
import Close24SVG from "./icons/regular/close.svg";
import CloseXs24SVG from "./icons/regular/close-xs.svg";
import CloseSmall24SVG from "./icons/regular/close-small.svg";
import CloseNotification24SVG from "./icons/regular/close-notification.svg";
import CloseHamburger24SVG from "./icons/regular/close-hamburger.svg";
import Clock24SVG from "./icons/regular/clock.svg";
import ClearSmall24SVG from "./icons/regular/clear-small.svg";
import Checkmark24SVG from "./icons/regular/checkmark.svg";
import CheckmarkS24SVG from "./icons/regular/checkmark-s.svg";
import CheckmarkBlueDark24SVG from "./icons/regular/checkmark-blue-dark.svg";
import Checklist24SVG from "./icons/regular/checklist.svg";
import CheckWhite24SVG from "./icons/regular/check-white.svg";
import Chat24SVG from "./icons/regular/chat.svg";
import CartFull24SVG from "./icons/regular/cart-full.svg";
import CartEmpty24SVG from "./icons/regular/cart-empty.svg";
import Caret24SVG from "./icons/regular/caret.svg";
import CaretUp24SVG from "./icons/regular/caret-up.svg";
import CaretRight24SVG from "./icons/regular/caret-right.svg";
import CaretLeft24SVG from "./icons/regular/caret-left.svg";
import CaretDown24SVG from "./icons/regular/caret-down.svg";
import Calendar24SVG from "./icons/regular/calendar.svg";
import BuildingOps24SVG from "./icons/regular/building-ops.svg";
import Bookmark24SVG from "./icons/regular/bookmark.svg";
import Billing24SVG from "./icons/regular/billing.svg";
import Back24SVG from "./icons/regular/back.svg";
import Attachment24SVG from "./icons/regular/attachment.svg";
import Attach24SVG from "./icons/regular/attach.svg";
import Assets24SVG from "./icons/regular/assets.svg";
import AreaPost24SVG from "./icons/regular/area-post.svg";
import Archive24SVG from "./icons/regular/archive.svg";
import Add24SVG from "./icons/regular/add.svg";
import AddMember24SVG from "./icons/regular/add-member.svg";
import AddFolder24SVG from "./icons/regular/add-folder.svg";
import names from "./release/hig-icon-names.json";
import sets from "./release/hig-icon-sets.json";
import { sizes, AVAILABLE_SIZES } from "./sizes";

const AVAILABLE_NAMES = Object.freeze(Object.values(names));
export { AVAILABLE_NAMES, names, sets, sizes, AVAILABLE_SIZES };

export const AddFolder24 = AddFolder24SVG;
export const AddMember24 = AddMember24SVG;
export const Add24 = Add24SVG;
export const Archive24 = Archive24SVG;
export const AreaPost24 = AreaPost24SVG;
export const Assets24 = Assets24SVG;
export const Attach24 = Attach24SVG;
export const Attachment24 = Attachment24SVG;
export const Back24 = Back24SVG;
export const Billing24 = Billing24SVG;
export const Bookmark24 = Bookmark24SVG;
export const BuildingOps24 = BuildingOps24SVG;
export const Calendar24 = Calendar24SVG;
export const CaretDown24 = CaretDown24SVG;
export const CaretLeft24 = CaretLeft24SVG;
export const CaretRight24 = CaretRight24SVG;
export const CaretUp24 = CaretUp24SVG;
export const Caret24 = Caret24SVG;
export const CartEmpty24 = CartEmpty24SVG;
export const CartFull24 = CartFull24SVG;
export const Chat24 = Chat24SVG;
export const CheckWhite24 = CheckWhite24SVG;
export const Checklist24 = Checklist24SVG;
export const CheckmarkBlueDark24 = CheckmarkBlueDark24SVG;
export const CheckmarkS24 = CheckmarkS24SVG;
export const Checkmark24 = Checkmark24SVG;
export const ClearSmall24 = ClearSmall24SVG;
export const Clock24 = Clock24SVG;
export const CloseHamburger24 = CloseHamburger24SVG;
export const CloseNotification24 = CloseNotification24SVG;
export const CloseSmall24 = CloseSmall24SVG;
export const CloseXs24 = CloseXs24SVG;
export const Close24 = Close24SVG;
export const ClosedCaptioning24 = ClosedCaptioning24SVG;
export const Cloud24 = Cloud24SVG;
export const Collaboration24 = Collaboration24SVG;
export const CollapsePanel24 = CollapsePanel24SVG;
export const Collapse24 = Collapse24SVG;
export const Comment24 = Comment24SVG;
export const Compare24 = Compare24SVG;
export const Complete24 = Complete24SVG;
export const Copy24 = Copy24SVG;
export const CostControl24 = CostControl24SVG;
export const CtaArrowRight24 = CtaArrowRight24SVG;
export const Dashboard24 = Dashboard24SVG;
export const DeviceDesktop24 = DeviceDesktop24SVG;
export const DeviceMobile24 = DeviceMobile24SVG;
export const DeviceTablet24 = DeviceTablet24SVG;
export const Devices24 = Devices24SVG;
export const DocumentManagement24 = DocumentManagement24SVG;
export const DoubleCaret24 = DoubleCaret24SVG;
export const Down24 = Down24SVG;
export const Download24 = Download24SVG;
export const Edit24 = Edit24SVG;
export const Education24 = Education24SVG;
export const Error24 = Error24SVG;
export const ExpandPanel24 = ExpandPanel24SVG;
export const Expand24 = Expand24SVG;
export const ExportMove24 = ExportMove24SVG;
export const Export24 = Export24SVG;
export const ExternalLink24 = ExternalLink24SVG;
export const External24 = External24SVG;
export const Favorite24 = Favorite24SVG;
export const Featured24 = Featured24SVG;
export const Feedback24 = Feedback24SVG;
export const Field24 = Field24SVG;
export const FileAssembly24 = FileAssembly24SVG;
export const FileDocument24 = FileDocument24SVG;
export const FileGeneric24 = FileGeneric24SVG;
export const FileImage24 = FileImage24SVG;
export const FilePart24 = FilePart24SVG;
export const FilePdf24 = FilePdf24SVG;
export const FilePresentation24 = FilePresentation24SVG;
export const FileSpreadsheet24 = FileSpreadsheet24SVG;
export const FileVideo24 = FileVideo24SVG;
export const FileZip24 = FileZip24SVG;
export const FilterTokens24 = FilterTokens24SVG;
export const Filter24 = Filter24SVG;
export const Flag24 = Flag24SVG;
export const FolderOpen24 = FolderOpen24SVG;
export const Folder24 = Folder24SVG;
export const Forums24 = Forums24SVG;
export const Forward24 = Forward24SVG;
export const Globe24 = Globe24SVG;
export const Grid24 = Grid24SVG;
export const HamburgerClose24 = HamburgerClose24SVG;
export const HamburgerDefault24 = HamburgerDefault24SVG;
export const Hamburger24 = Hamburger24SVG;
export const Help24 = Help24SVG;
export const Hidden24 = Hidden24SVG;
export const Hierarchy24 = Hierarchy24SVG;
export const Home24 = Home24SVG;
export const Info24 = Info24SVG;
export const Insight24 = Insight24SVG;
export const Issue24 = Issue24SVG;
export const Item24 = Item24SVG;
export const Layout24 = Layout24SVG;
export const Link24 = Link24SVG;
export const List24 = List24SVG;
export const Location24 = Location24SVG;
export const Lock24 = Lock24SVG;
export const Mail24 = Mail24SVG;
export const ManageAccess24 = ManageAccess24SVG;
export const Maximize24 = Maximize24SVG;
export const Minimize24 = Minimize24SVG;
export const ModelCoordination24 = ModelCoordination24SVG;
export const MoreVertical24 = MoreVertical24SVG;
export const More24 = More24SVG;
export const Notification24 = Notification24SVG;
export const OnlineViewers24 = OnlineViewers24SVG;
export const Paste24 = Paste24SVG;
export const Pause24 = Pause24SVG;
export const PermissionGroup24 = PermissionGroup24SVG;
export const PermissionIndividual24 = PermissionIndividual24SVG;
export const Photos24 = Photos24SVG;
export const Pin24 = Pin24SVG;
export const Placeholder24 = Placeholder24SVG;
export const Play24 = Play24SVG;
export const Print24 = Print24SVG;
export const ProductsAndServices24 = ProductsAndServices24SVG;
export const Profile24 = Profile24SVG;
export const ProjectManagement24 = ProjectManagement24SVG;
export const Properties24 = Properties24SVG;
export const Publish24 = Publish24SVG;
export const Quantities24 = Quantities24SVG;
export const Recommend24 = Recommend24SVG;
export const Redo24 = Redo24SVG;
export const Report24 = Report24SVG;
export const Rfi24 = Rfi24SVG;
export const Save24 = Save24SVG;
export const Search24 = Search24SVG;
export const Security24 = Security24SVG;
export const Service24 = Service24SVG;
export const Settings24 = Settings24SVG;
export const Share24 = Share24SVG;
export const SocialBlog224 = SocialBlog224SVG;
export const SocialBlog24 = SocialBlog24SVG;
export const SocialFacebook24 = SocialFacebook24SVG;
export const SocialInstagram24 = SocialInstagram24SVG;
export const SocialLinkedin24 = SocialLinkedin24SVG;
export const SocialTwitter24 = SocialTwitter24SVG;
export const SocialYoutube24 = SocialYoutube24SVG;
export const Subscription24 = Subscription24SVG;
export const Support24 = Support24SVG;
export const Sync24 = Sync24SVG;
export const Tag24 = Tag24SVG;
export const Trash24 = Trash24SVG;
export const Unavailable24 = Unavailable24SVG;
export const Undo24 = Undo24SVG;
export const Unlock24 = Unlock24SVG;
export const Up24 = Up24SVG;
export const Upload24 = Upload24SVG;
export const Visible24 = Visible24SVG;
export const Volume24 = Volume24SVG;
export const XCloseGray24 = XCloseGray24SVG;
export const ZoomIn24 = ZoomIn24SVG;
export const ZoomOut24 = ZoomOut24SVG;
export const AddFolder16 = AddFolder16SVG;
export const AddMember16 = AddMember16SVG;
export const Add16 = Add16SVG;
export const Archive16 = Archive16SVG;
export const AreaPost16 = AreaPost16SVG;
export const Assets16 = Assets16SVG;
export const Attach16 = Attach16SVG;
export const Attachment16 = Attachment16SVG;
export const Back16 = Back16SVG;
export const Billing16 = Billing16SVG;
export const Bookmark16 = Bookmark16SVG;
export const BuildingOps16 = BuildingOps16SVG;
export const Calendar16 = Calendar16SVG;
export const CaretDown16 = CaretDown16SVG;
export const CaretLeft16 = CaretLeft16SVG;
export const CaretRight16 = CaretRight16SVG;
export const CaretUp16 = CaretUp16SVG;
export const CartEmpty16 = CartEmpty16SVG;
export const CartFull16 = CartFull16SVG;
export const Chat16 = Chat16SVG;
export const CheckDisabled16 = CheckDisabled16SVG;
export const CheckboxChecked16 = CheckboxChecked16SVG;
export const CheckboxIndeterminate16 = CheckboxIndeterminate16SVG;
export const Checklist16 = Checklist16SVG;
export const CheckmarkIndeterminate16 = CheckmarkIndeterminate16SVG;
export const Checkmark16 = Checkmark16SVG;
export const Clock16 = Clock16SVG;
export const CloseSmall16 = CloseSmall16SVG;
export const Close16 = Close16SVG;
export const ClosedCaptioning16 = ClosedCaptioning16SVG;
export const Cloud16 = Cloud16SVG;
export const Collaboration16 = Collaboration16SVG;
export const CollapsePanel16 = CollapsePanel16SVG;
export const Comment16 = Comment16SVG;
export const Compare16 = Compare16SVG;
export const Complete16 = Complete16SVG;
export const Copy16 = Copy16SVG;
export const CostControl16 = CostControl16SVG;
export const CtaArrowRight16 = CtaArrowRight16SVG;
export const Dashboard16 = Dashboard16SVG;
export const DeviceDesktop16 = DeviceDesktop16SVG;
export const DeviceMobile16 = DeviceMobile16SVG;
export const DeviceTablet16 = DeviceTablet16SVG;
export const Devices16 = Devices16SVG;
export const DocumentManagement16 = DocumentManagement16SVG;
export const Down16 = Down16SVG;
export const Download16 = Download16SVG;
export const DropdownCaretDown16 = DropdownCaretDown16SVG;
export const DropdownCaretLeft16 = DropdownCaretLeft16SVG;
export const DropdownCaretRight16 = DropdownCaretRight16SVG;
export const DropdownCaretUp16 = DropdownCaretUp16SVG;
export const Edit16 = Edit16SVG;
export const Education16 = Education16SVG;
export const Error16 = Error16SVG;
export const ExpandPanel16 = ExpandPanel16SVG;
export const ExportMove16 = ExportMove16SVG;
export const Export16 = Export16SVG;
export const ExternalLink16 = ExternalLink16SVG;
export const External16 = External16SVG;
export const Favorite16 = Favorite16SVG;
export const Featured16 = Featured16SVG;
export const Feedback16 = Feedback16SVG;
export const Field16 = Field16SVG;
export const FileAssembly16 = FileAssembly16SVG;
export const FileDocument16 = FileDocument16SVG;
export const FileGeneric16 = FileGeneric16SVG;
export const FileImage16 = FileImage16SVG;
export const FilePart16 = FilePart16SVG;
export const FilePdf16 = FilePdf16SVG;
export const FilePresentation16 = FilePresentation16SVG;
export const FileSpreadsheet16 = FileSpreadsheet16SVG;
export const FileVideo16 = FileVideo16SVG;
export const FileZip16 = FileZip16SVG;
export const FilterTokens16 = FilterTokens16SVG;
export const Filter16 = Filter16SVG;
export const Flag16 = Flag16SVG;
export const FolderOpen16 = FolderOpen16SVG;
export const Folder16 = Folder16SVG;
export const Forums16 = Forums16SVG;
export const Forward16 = Forward16SVG;
export const Globe16 = Globe16SVG;
export const Grid16 = Grid16SVG;
export const Help16 = Help16SVG;
export const Hidden16 = Hidden16SVG;
export const Hierarchy16 = Hierarchy16SVG;
export const Home16 = Home16SVG;
export const Info16 = Info16SVG;
export const Insight16 = Insight16SVG;
export const Issue16 = Issue16SVG;
export const Item16 = Item16SVG;
export const Layout16 = Layout16SVG;
export const Link16 = Link16SVG;
export const List16 = List16SVG;
export const Location16 = Location16SVG;
export const Lock16 = Lock16SVG;
export const Mail16 = Mail16SVG;
export const ManageAccess16 = ManageAccess16SVG;
export const Maximize16 = Maximize16SVG;
export const Minimize16 = Minimize16SVG;
export const ModelCoordination16 = ModelCoordination16SVG;
export const MoreVertical16 = MoreVertical16SVG;
export const More16 = More16SVG;
export const Notification16 = Notification16SVG;
export const OnlineViewers16 = OnlineViewers16SVG;
export const Paste16 = Paste16SVG;
export const Pause16 = Pause16SVG;
export const PermissionGroup16 = PermissionGroup16SVG;
export const PermissionIndividual16 = PermissionIndividual16SVG;
export const Photos16 = Photos16SVG;
export const Pin16 = Pin16SVG;
export const Placeholder16 = Placeholder16SVG;
export const Play16 = Play16SVG;
export const Print16 = Print16SVG;
export const ProductsAndServices16 = ProductsAndServices16SVG;
export const Profile16 = Profile16SVG;
export const ProjectManagement16 = ProjectManagement16SVG;
export const Properties16 = Properties16SVG;
export const Publish16 = Publish16SVG;
export const Quantities16 = Quantities16SVG;
export const Recommend16 = Recommend16SVG;
export const Redo16 = Redo16SVG;
export const Report16 = Report16SVG;
export const Rfi16 = Rfi16SVG;
export const Save16 = Save16SVG;
export const Search16 = Search16SVG;
export const Security16 = Security16SVG;
export const Service16 = Service16SVG;
export const Settings16 = Settings16SVG;
export const Share16 = Share16SVG;
export const SocialFacebook16 = SocialFacebook16SVG;
export const SocialInstagram16 = SocialInstagram16SVG;
export const SocialLinkedin16 = SocialLinkedin16SVG;
export const SocialTwitter16 = SocialTwitter16SVG;
export const SocialYoutube16 = SocialYoutube16SVG;
export const Subscription16 = Subscription16SVG;
export const Support16 = Support16SVG;
export const Sync16 = Sync16SVG;
export const Tag16 = Tag16SVG;
export const Trash16 = Trash16SVG;
export const Unavailable16 = Unavailable16SVG;
export const Undo16 = Undo16SVG;
export const Unlock16 = Unlock16SVG;
export const Up16 = Up16SVG;
export const Upload16 = Upload16SVG;
export const Visible16 = Visible16SVG;
export const Volume16 = Volume16SVG;
export const ZoomIn16 = ZoomIn16SVG;
export const ZoomOut16 = ZoomOut16SVG;
