export default {
  "SPACINGS.XS": { ref: "BASICS.SPACINGS.XS" },
  "SPACINGS.S": { ref: "BASICS.SPACINGS.S" },
  "SPACINGS.M": { ref: "BASICS.SPACINGS.M" },
  "SPACINGS.L": { ref: "BASICS.SPACINGS.L" },
  "SPACINGS.XL": { ref: "BASICS.SPACINGS.XL" },
  "FONT_SIZES.S": { ref: "BASICS.FONT_SIZES.S" },
  "FONT_SIZES.M": { ref: "BASICS.FONT_SIZES.M" },
  "FONT_SIZES.L": { ref: "BASICS.FONT_SIZES.L" }
};
