import React from "react";
import { storiesOf } from "@storybook/react";
import Icon from "elements/components/Icon/Icon";

const styles = {
  display: "flex",
  flexDirection: "row",
  flexWrap: "wrap",
  maxWidth: "400px"
};

const iconKeys = [
  "add",
  "archive",
  "assets",
  "attachment",
  "back",
  "bookmark",
  "building-ops",
  "calendar",
  "caret",
  "check-white",
  "checklist",
  "checkmark-blue-dark",
  "checkmark",
  "clear-small",
  "clock",
  "close-hamburger",
  "close-small",
  "close",
  "collaboration",
  "collapse-panel",
  "collapse",
  "comment",
  "compare",
  "complete",
  "copy",
  "cost-control",
  "document-management",
  "double-caret",
  "download",
  "edit",
  "expand-panel",
  "expand",
  "export",
  "external",
  "external-link",
  "favorite",
  "field",
  "file-assembly",
  "file-document",
  "file-generic",
  "file-image",
  "file-part",
  "file-pdf",
  "file-presentation",
  "file-spreadsheet",
  "file-video",
  "file-zip",
  "filter-tokens",
  "filter",
  "folder-open",
  "folder",
  "forward",
  "globe",
  "grid",
  "hamburger",
  "help",
  "hidden",
  "home",
  "insight",
  "issue",
  "item",
  "layout",
  "list",
  "location",
  "lock",
  "model-coordination",
  "paste",
  "permission-group",
  "permission-individual",
  "photos",
  "play",
  "print",
  "profile",
  "project-management",
  "publish",
  "quantities",
  "redo",
  "rfi",
  "save",
  "search",
  "settings",
  "share",
  "sync",
  "tag",
  "trash",
  "undo",
  "unlock",
  "upload",
  "visible",
  "x-close-gray"
];

const iconKeys16 = [
  "add",
  "archive",
  "assets",
  "attachment",
  "back",
  "bookmark",
  "building-ops",
  "calendar",
  "checklist",
  "checkmark",
  "clock",
  "close",
  "collaboration",
  "collapse-panel",
  "comment",
  "compare",
  "complete",
  "copy",
  "cost-control",
  "document-management",
  "download",
  "edit",
  "expand-panel",
  "export",
  "external",
  "external-link",
  "favorite",
  "field",
  "file-assembly",
  "file-document",
  "file-generic",
  "file-image",
  "file-part",
  "file-pdf",
  "file-presentation",
  "file-spreadsheet",
  "file-video",
  "file-zip",
  "filter",
  "filter-tokens",
  "folder",
  "folder-open",
  "forward",
  "globe",
  "grid",
  "help",
  "hidden",
  "home",
  "insight",
  "issue",
  "item",
  "layout",
  "list",
  "location",
  "lock",
  "model-coordination",
  "paste",
  "permission-group",
  "permission-individual",
  "photos",
  "play",
  "print",
  "profile",
  "project-management",
  "publish",
  "quantities",
  "redo",
  "rfi",
  "save",
  "search",
  "settings",
  "share",
  "sync",
  "tag",
  "trash",
  "undo",
  "unlock",
  "upload",
  "visible"
];

storiesOf("Icon", module).add("size 24", () => (
  <div style={styles}>
    {iconKeys.map(key => (
      <div style={{ paddingRight: "5px" }} key={key}>
        <Icon nameOrSVG={key} key={key} size="24" />
      </div>
    ))}
  </div>
));

storiesOf("Icon", module).add("size 16", () => (
  <div style={styles}>
    {iconKeys16.map(key => (
      <div style={{ paddingRight: "5px" }} key={key}>
        <Icon nameOrSVG={key} key={key} size="16" />
      </div>
    ))}
  </div>
));
