export default {
  "MENU.BACKGROUND_COLOR": { ref: "COLOR_SCHEME.COMPONENT.BACKGROUND_COLOR" },
  "MENU.BORDER_RADIUS": { ref: "BASICS.BORDER_RADII.M" },
  "MENU.TOP_FLUSH_BORDER_TOP_RADIUS": { ref: "BASICS.BORDER_RADII.NONE" },
  "MENU.ITEM.BACKGROUND_COLOR": {
    ref: "COLOR_SCHEME.COMPONENT.BACKGROUND_COLOR"
  },
  "MENU.ITEM.HOVER.BACKGROUND_COLOR": {
    ref: "BASICS.COLORS.CHARCOAL_600",
    transform: { alpha: 0.1 }
  },
  "MENU.ITEM.FOCUS.BACKGROUND_COLOR": {
    ref: "MENU.ITEM.HOVER.BACKGROUND_COLOR"
  },
  "MENU.ITEM.ACTIVE.BACKGROUND_COLOR": {
    ref: "COLOR_SCHEME.ACCENT_COLOR_500",
    transform: { alpha: 0.1 }
  },
  "MENU.ITEM.HORIZONTAL_PADDING": { ref: "DENSITY.SPACINGS.XS" },
  "MENU.ITEM.VERTICAL_PADDING": { ref: "BASICS.SPACINGS.MEDIUM_S" },
  "MENU.ITEM.MIN_HEIGHT": { ref: "DENSITY.MENU.ITEM.MIN_HEIGHT" },
  "MENU.ITEM.GRID_GUTTER_WIDTH": { ref: "BASICS.SPACINGS.MEDIUM_S" }
};
