export default {
  CHECKBOX_BACKGROUND_COLOR: { ref: "COLOR_SCHEME.COMPONENT_BACKGROUND_COLOR" },
  CHECKBOX_CHECKED_BACKGROUND_COLOR: { ref: "BASICS.COLORS.CHARCOAL_600" },
  CHECKBOX_DISABLED_CHECKED_BACKGROUND_COLOR: {
    ref: "BASICS.COLORS.CHARCOAL_600",
    transform: { alhpa: 0.5 }
  },
  CHECKBOX_BORDER_WIDTH: { ref: "INPUT_BORDER_BOTTOM_WIDTH" },
  CHECKBOX_BORDER_COLOR: {
    ref: "BASICS.COLORS.CHARCOAL_600",
    transform: { alpha: 0.5 }
  },
  CHECKBOX_CHECKED_BORDER_COLOR: { ref: "BASICS.COLORS.CHARCOAL_600" },
  CHECKBOX_CHECKED_ICON_COLOR: { ref: "BASICS.COLORS.WHITE" },
  CHECKBOX_HALO_COLOR: { ref: "INPUT_HALO_COLOR" },
  CHECKBOX_HALO_HOVER_WIDTH: { ref: "INPUT_HALO_HOVER_WIDTH" },
  CHECKBOX_HALO_FOCUS_COLOR: { ref: "INPUT_HALO_FOCUS_COLOR" },
  CHECKBOX_HALO_FOCUS_WIDTH: { ref: "INPUT_HALO_FOCUS_WIDTH" },
  CHECKBOX_HALO_ACTIVE_COLOR: { ref: "INPUT_HALO_ACTIVE_COLOR" },
  CHECKBOX_HALO_ACTIVE_WIDTH: { ref: "INPUT_HALO_ACTIVE_WIDTH" }
};
