export default {
  "CHECKBOX.BACKGROUND_COLOR": {
    ref: "COLOR_SCHEME.COMPONENT.BACKGROUND_COLOR"
  },
  "CHECKBOX.CHECKED.BACKGROUND_COLOR": { ref: "BASICS.COLORS.CHARCOAL_600" },
  "CHECKBOX.DISABLED.CHECKED.BACKGROUND_COLOR": {
    ref: "BASICS.COLORS.CHARCOAL_600",
    transform: { alhpa: 0.5 }
  },
  "CHECKBOX.BORDER_WIDTH": { ref: "INPUT.BORDER_BOTTOM_WIDTH" },
  "CHECKBOX.BORDER_COLOR": {
    ref: "BASICS.COLORS.CHARCOAL_600",
    transform: { alpha: 0.5 }
  },
  "CHECKBOX.CHECKED.BORDER_COLOR": { ref: "BASICS.COLORS.CHARCOAL_600" },
  "CHECKBOX.CHECKED.ICON_COLOR": { ref: "BASICS.COLORS.WHITE" },
  "CHECKBOX.HALO.COLOR": { ref: "INPUT.HALO.COLOR" },
  "CHECKBOX.HOVER.HALO.WIDTH": { ref: "INPUT.HOVER.HALO.WIDTH" },
  "CHECKBOX.FOCUS.HALO.COLOR": { ref: "INPUT.FOCUS.HALO.COLOR" },
  "CHECKBOX.FOCUS.HALO.WIDTH": { ref: "INPUT.FOCUS.HALO.WIDTH" },
  "CHECKBOX.ACTIVE.HALO.COLOR": { ref: "INPUT.ACTIVE.HALO.COLOR" },
  "CHECKBOX.ACTIVE.HALO.WIDTH": { ref: "INPUT.ACTIVE.HALO.WIDTH" }
};
