export default {
  INPUT_MIN_HEIGHT: { ref: "DENSITY.INPUT_MIN_HEIGHT" },
  INPUT_VERTICAL_PADDING: { ref: "DENSITY.INPUT_VERTICAL_PADDING" },
  INPUT_DENSITY_MEDIUM_MIN_HEIGHT: "24px",
  INPUT_GRID_GUTTER_WIDTH: { ref: "DENSITY.SPACINGS.S" },
  INPUT_BORDER_BOTTOM_COLOR: { abstract: true },
  INPUT_BORDER_BOTTOM_WIDTH: { ref: "BASICS.BORDER_WIDTHS.S" },
  INPUT_BORDER_BOTTOM_HOVER_COLOR: { abstract: true },
  INPUT_BORDER_BOTTOM_FOCUS_COLOR: { abstract: true },
  INPUT_HALO_COLOR: { abstract: true },
  INPUT_HALO_HOVER_WIDTH: { ref: "BASICS.BORDER_WIDTHS.L" },
  INPUT_HALO_FOCUS_WIDTH: { ref: "BASICS.BORDER_WIDTHS.L" },
  INPUT_HALO_FOCUS_COLOR: { abstract: true },
  INPUT_HALO_ACTIVE_WIDTH: { ref: "BASICS.BORDER_WIDTHS.L" },
  INPUT_HALO_ACTIVE_COLOR: { abstract: true }
};
