export default {
  "LABEL.FONT_SIZE": { ref: "DENSITY.FONT_SIZES.S" },
  "LABEL.FONT_WEIGHT": { ref: "BASICS.FONT_WEIGHTS.REGULAR" },
  "LABEL.FONT_FAMILY": { ref: "BASICS.FONT_FAMILIES.MAIN" },
  "LABEL.FONT_COLOR": { abstract: true },
  "LABEL.LINE_HEIGHT": { ref: "BASICS.LINE_HEIGHTS.M" },
  "LABEL.DISABLED.FONT_COLOR": { abstract: true }
};
