export default {
  LABEL_FONT_SIZE: { ref: "DENSITY.FONT_SIZES.S" },
  LABEL_FONT_WEIGHT: { ref: "BASICS.FONT_WEIGHTS.REGULAR" },
  LABEL_FONT_FAMILY: { ref: "BASICS.FONT_FAMILIES.MAIN" },
  LABEL_FONT_COLOR: { abstract: true },
  LABEL_LINE_HEIGHT: { ref: "BASICS.LINE_HEIGHTS.M" },
  LABEL_DISABLED_FONT_COLOR: { abstract: true }
};
