export default {
  MENU_BACKGROUND_COLOR: { ref: "COLOR_SCHEME.COMPONENT_BACKGROUND_COLOR" },
  MENU_BORDER_RADIUS: { ref: "BASICS.BORDER_RADII.M" },
  MENU_TOP_FLUSH_BORDER_TOP_RADIUS: { ref: "BASICS.BORDER_RADII.NONE" },
  MENU_ITEM_BACKGROUND_COLOR: {
    ref: "COLOR_SCHEME.COMPONENT_BACKGROUND_COLOR"
  },
  MENU_ITEM_BACKGROUND_HOVER_COLOR: {
    ref: "BASICS.COLORS.CHARCOAL_600",
    transform: { alpha: 0.1 }
  },
  MENU_ITEM_BACKGROUND_FOCUS_COLOR: { ref: "MENU_ITEM_BACKGROUND_HOVER_COLOR" },
  MENU_ITEM_BACKGROUND_ACTIVE_COLOR: {
    ref: "COLOR_SCHEME.ACCENT_COLOR_500",
    transform: { alpha: 0.1 }
  },
  MENU_ITEM_HORIZONTAL_PADDING: { ref: "DENSITY.SPACINGS.XS" },
  MENU_ITEM_VERTICAL_PADDING: { ref: "BASICS.SPACINGS.S" },
  MENU_ITEM_MIN_HEIGHT: { ref: "DENSITY.MENU_ITEM_MIN_HEIGHT" },
  MENU_ITEM_GRID_GUTTER_WIDTH: { ref: "BASICS.SPACINGS.S" }
};
