export default {
  SURFACE_LEVEL_1_COLOR: { ref: "BASICS.COLORS.SURFACE_LIGHT_GRAY_LEVEL_1" },
  SURFACE_LEVEL_1_5_COLOR: {
    ref: "BASICS.COLORS.SURFACE_LIGHT_GRAY_LEVEL_1_5"
  },
  SURFACE_LEVEL_2_COLOR: { ref: "BASICS.COLORS.SURFACE_LIGHT_GRAY_LEVEL_2" },
  SURFACE_LEVEL_3_COLOR: { ref: "BASICS.COLORS.SURFACE_LIGHT_GRAY_LEVEL_3" },
  SURFACE_LEVEL_4_COLOR: { ref: "BASICS.COLORS.SURFACE_LIGHT_GRAY_LEVEL_4" },
  LOW_SHADOW_COLOR: {
    ref: "BASICS.COLORS.SURFACE_LIGHT_GRAY_SHADOW",
    transform: { alpha: 0.25 }
  },
  HIGH_SHADOW_COLOR: {
    ref: "BASICS.COLORS.SURFACE_LIGHT_GRAY_SHADOW",
    transform: { alpha: 0.25 }
  },
  ACCENT_COLOR_100: { ref: "BASICS.COLORS.AUTODESK_BLUE_100" },
  ACCENT_COLOR_200: { ref: "BASICS.COLORS.AUTODESK_BLUE_200" },
  ACCENT_COLOR_300: { ref: "BASICS.COLORS.AUTODESK_BLUE_300" },
  ACCENT_COLOR_400: { ref: "BASICS.COLORS.AUTODESK_BLUE_400" },
  ACCENT_COLOR_500: { ref: "BASICS.COLORS.AUTODESK_BLUE_500" },
  ACCENT_COLOR_600: { ref: "BASICS.COLORS.AUTODESK_BLUE_600" },
  ACCENT_COLOR_700: { ref: "BASICS.COLORS.AUTODESK_BLUE_700" },
  ACCENT_COLOR_800: { ref: "BASICS.COLORS.AUTODESK_BLUE_800" },
  ACCENT_COLOR_900: { ref: "BASICS.COLORS.AUTODESK_BLUE_900" },
  TEXT_COLOR: { ref: "BASICS.COLORS.TEXT_AGAINST_LIGHT" },
  "COMPONENT.BACKGROUND_COLOR": { ref: "BASICS.COLORS.WHITE" }
};
